# Generated by Django 5.1.3 on 2024-11-24 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codigo_naci', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id_tipo_habitacion', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('nombre_tipo_hab', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=22, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=25, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(blank=True, max_length=18, null=True)),
                ('codigo_naci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('pago_total', models.IntegerField(null=True)),
                ('metodo_Pago', models.CharField(max_length=18, null=True)),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('n_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado_habitacion', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_usuario', models.CharField(blank=True, max_length=25, null=True)),
                ('tipo_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('nro_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(blank=True, null=True)),
                ('estado_reserva', models.CharField(blank=True, max_length=22, null=True)),
                ('flag_particular', models.BooleanField(default=False)),
                ('cantidad_persona', models.IntegerField(blank=True, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=40, null=True)),
                ('cantidad_dias', models.IntegerField(blank=True, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.habitacion')),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.pasajero')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservas.pago')),
                ('numero_linea', models.IntegerField()),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('id_servicios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.servicios')),
            ],
        ),
    ]
