# Generated by Django 5.1.3 on 2024-11-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='metodo_Pago',
            new_name='metodo_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pasajero',
            field=models.ForeignKey(db_column='id_pasajero', on_delete=django.db.models.deletion.CASCADE, to='reservas.pasajero'),
        ),
    ]
